stages:
  prepare:
    cmd: python src/prepare.py data/raw/wachttijden.csv
    deps:
    - data/raw/wachttijden.csv
    - src/prepare.py
    params:
    - prepare.split
    outs:
    - data/prepared/wachttijden.csv
