stages:
  prepare:
    cmd: python src/prepare.py data/raw/wachttijden.csv data/intermediate/wachttijden.csv
    deps:
    - data/raw/wachttijden.csv
    - src/prepare.py
    outs:
    - data/intermediate/wachttijden.csv
