name: train_model
on:
  push:
    branches:
      - main
jobs:
  train_model:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          pip install -r requirements.txt
          dvc pull --run-cache
          dvc repro

          # Report metrics
          git fetch --prune
          git config --global --add safe.directory /__w/dvc-demo/dvc-demo
          dvc metrics diff main --show-md >> report.md

          # Send report as a comment
          cml send-comment report.md

