name: train_model
on:
  push:
    branches:
      - main
jobs:
  train_model:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          # Install the python requirements
          pip install -r requirements.txt

          # Pull the data and reproduce the experiment
          dvc pull
          dvc repro

          # Report metrics
          git fetch --prune --unshallow
          dvc metrics diff main --show-md >> report.md

          # Send report as a comment
          cml comment create --pr --publish report.md
